name: try_catch
description: try call a async function , return value same as the function, on exception print error and ignore
version: 1.0.1
homepage: https://github.com/rmw-dart/try_catch

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

